---
title: "get_open_data"
author: "Ravi Brenner"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(socratadata)
library(sf)
```

## Read collisions data
```{r}
collisions <- soc_read("https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95/about_data",
                       query = soc_query(
                         where = "crash_date >= '2020-01-01'"
                       ))
```

save as csv

Need to split into years for github file size limit
```{r}
write_csv(collisions |>
            select(-location,-starts_with(":")) |>
            filter(year(crash_date) == 2020),
          "data/collisions_2020.csv")

write_csv(collisions |>
            select(-location,-starts_with(":")) |>
            filter(year(crash_date) == 2021),
          "data/collisions_2021.csv")

write_csv(collisions |>
            select(-location,-starts_with(":")) |>
            filter(year(crash_date) == 2022),
          "data/collisions_2022.csv")

write_csv(collisions |>
            select(-location,-starts_with(":")) |>
            filter(year(crash_date) == 2023),
          "data/collisions_2023.csv")

write_csv(collisions |>
            select(-location,-starts_with(":")) |>
            filter(year(crash_date) == 2024),
          "data/collisions_2024.csv")

write_csv(collisions |>
            select(-location,-starts_with(":")) |>
            filter(year(crash_date) == 2025),
          "data/collisions_2025.csv")

```


## Read in bike routes data
```{r}
bike_routes <- soc_read("https://data.cityofnewyork.us/dataset/New-York-City-Bike-Routes/mzxg-pwib/about_data")
```

Save as csv and .shp
```{r}
write_csv(bike_routes |>
           select(-starts_with(":")),
          "data/nyc_bike_routes.csv")

st_write(bike_routes |>
           select(-starts_with(":")),
         "data/nyc_bike_routes.shp",
         delete_layer = TRUE)
```

## Bike counts
```{r}
bike_counts <- soc_read("https://data.cityofnewyork.us/Transportation/Bicycle-Counts/uczf-rk3c/about_data",
                        query = soc_query(
                          where = "date >= '2020-01-01'"
                        ))
```

Save as csv
```{r}
write_csv(bike_counts |>
            select(-starts_with(":")) |>
            filter(year(date) == 2020),
          "data/bike_counts_2020.csv")

write_csv(bike_counts |>
            select(-starts_with(":")) |>
            filter(year(date) == 2021),
          "data/bike_counts_2021.csv")

write_csv(bike_counts |>
            select(-starts_with(":")) |>
            filter(year(date) == 2022),
          "data/bike_counts_2022.csv")

write_csv(bike_counts |>
            select(-starts_with(":")) |>
            filter(year(date) == 2023),
          "data/bike_counts_2023.csv")

write_csv(bike_counts |>
            select(-starts_with(":")) |>
            filter(year(date) == 2024),
          "data/bike_counts_2024.csv")

write_csv(bike_counts |>
            select(-starts_with(":")) |>
            filter(year(date) == 2025),
          "data/bike_counts_2025.csv")
```

## Bike counters
```{r}
bike_counters <- soc_read("https://data.cityofnewyork.us/Transportation/Bicycle-Counters/smn3-rzf9/about_data")
```

Save as csv
```{r}
write_csv(bike_counters,
          "data/bike_counters.csv")
```


